//array of sentences for random questions
export const array = ['If you could have any superpower what would it be?',
 'If you could be any animal, what would it be?',
 'What is your favourite day of the week?',
 'What would you do if you won one million pounds?',
 'Where is your favourite place to travel to?', 
 'What is your favourite season?',
 'What is your guilty pleasure?', 
 'Have you ever met anyone famous?',
 'What is your favourite song?',
 'What is your favourite movie?',
 'What was your favourite TV show growing up?',
 'Have you ever lived in another country?',
 'In your opinion, what is the most beautiful place on earth?',
 'Do you have any pets?',
 'Are you afraid of any animals?',
 'What is your favourite mythological creature?',
'What is your favorite restaurant?',
 'If you could only eat one item of food for the rest of your life, what would you eat?',
 'What is your favorite type of sweets?',
 'Sweet, salty, or sour?',
 'What’s the weirdest food you’ve ever eaten?',
 'What is something you are great at cooking?',
 'What is something you can’t cook?',
 'What is your favorite dessert?',
 'If you could eliminate one food so no one could eat it ever again, what would you destroy?',
 'What is your favorite breakfast?',
 'What is your favorite lunch?',
 'What is your favorite dinner?',
 'What is your favorite hobby?',
 'What is your favorite thing to do by yourself?',
 'What is your favorite sport or physical activity?',
 'What crazy activities do you dream of trying someday?',
 'What is your idea of fun?',
 'What two things do you consider yourself to be very good at?',
 'What two things do you consider yourself to be very bad at?',
 'If money and time were no object, what would you be doing right now?',
 'What is something you hate doing? Why?',
 'What is something you love doing? Why?',
 'Do you have any hidden talents?',
 'What was one new experience you tried that was completely unknown or uncomfortable to you at the time you tried it?',
 'If you had to delete all but 3 apps from your smartphone, which ones would you keep?',
 'When did you get your first mobile phone? What kind was it?',
 'If you had to choose between only having a mobile phone or a car for the rest of your life, which would you choose?',
 'How many Facebook friends do you have? How many of them do you actually communicate with?',
 'What technology innovation made the biggest impact on your life?',
 'Desktop, laptop, or tablet? Which do you prefer to use?',
 'What is your favorite thing about technology?',
 'What is your least favorite thing about technology?',
 'Where would you time-travel, if it were possible?',
 'If you could have a superpower, what would it be and why?',
 'If you were the captain of a pirate ship, what would be the name of your ship?',
 'If you could travel to any other planet (real or fictional), where would you go and why?',
 'Who is your favorite actor/actress?',
 'What is your favorite book?',
 'What series on Netflix did you binge watch embarrassingly fast?',
 'If you could be any fictional character, who would you be?',
 'What type of music do you listen to?',
 'What movie can you rewatch over and over again?',
 'If you could go back in time and make little changes to your childhood, what is one thing you’d learn and master over the years so you’d be an expert at it today?',
 'How would you change your life today if the average life expectancy was 400 years?',
 'What is the most challenging job you can think of?',
 'A genie grants you three wishes but none of them can directly benefit you. What would those wishes be?',
 'If you had to change your name, what would your new name be, and why would you choose that name?',
 'What are the best and worst purchases you’ve ever made?',
 'What is your biggest pet peeve?',
 'What is your most treasured material possession?',
 'What is your favorite smell and why?',
 'What do you never leave the house without other than your phone, keys or wallet?',
 'Who is your hero, and why?',
 'What is your earliest childhood memory?',
 'Who was your favorite teacher in school and how did he or she impact you?',
 'If you could choose an age to remain forever, which age would you choose?',
 'What is one important skill every person should have?',
 'What was the best thing that happened to you this year?',
 'Do you set New Years Resolutions? What was one of yours this year? Have you kept it?',
 'As a child, what did you want to be when you grew up?',
 'What is your least favorite job you’ve ever had?',
 'What is your favorite job you’ve ever had?',
 'What are you going to do when you retire?',
 'What is one important skill that you think everyone should have?',
 'There are now 25 hours in a day! How do you spend your extra hour?',
 'What “old person” things do you do?',
 'How long would you last in a zombie apocalypse?',
 'Who is your favorite cartoon character?',
 'What are your favorite songs from your teenage years?',
 'Who was your childhood actor/actress crush?',
 'What’s the craziest fashion trend you ever rocked?',
 'What did you get into the most trouble for with your parents as a kid?',
 'What’s the worst haircut you ever had?',
 'What’s the most ridiculous thing your parents ever did to embarrass you?',
 'As a kid, did you ever do something wrong but manage to pin it on your siblings?',
 'What is your favorite zoo animal?',
 'If you were a fish, what type would you be?',
 'If you had your human body, but the head of an animal, what animal would you pick?',
 'Are you a cat person or a dog person?',
 'What is your spirit animal? (The animal who is most similar to your personality.)',
 'Who is your favorite person to travel with?',
 'What is your favorite theme park?',
 'What’s your favorite thing about the place where you live?',
 'If you could live anywhere in the world for a year, where would it be?'
];

  export default {array};